- task: 'image_caption_tagger.v0'
  name: 'image_caption_tagger'
  
  # blip model config
  caption:
    model:
      model_name: 'Salesforce/blip2-opt-2.7b'
    device: 'cuda'
    batch_size: 20
    caption_column: 'caption'
    image_column: 'image'
  
  tagger:
    model:
      model_name: 'SmilingWolf/wd-v1-4-convnext-tagger-v2'
    device: 'cuda'
    batch_size: 40
    caption_column: 'tagger'
    image_column: 'image'
    filter_threshold: 0.5
  
  trigger_word: 'fengyizhou'
  caption_column: 'text'
  image_column: 'image'
  
  # input folder
  input:
    folder:
      image_folder: '../dataset/fengpig'
      patterns:
        - '*.JPG'
        - '*.png'
      recursive: True
  
  # output folder
  output:
    folder:
      image_folder: '../dataset/fengpig-blip' # if ignore, will use input_folder as output_folder
      metadata_name: 'metadata.json'