- task: 'image_caption_tagger.v0'
  name: 'image_caption_tagger'
  
  # # blip model config
  # caption_config:
  #   model:
  #     checkpoint: 'Salesforce/blip2-opt-2.7b'
  #   inference:
  #     device: 'cuda'
  #     batch_size: 20
  #     trigger_world: 'fengyizhou'
  
  tagger_config:
    model:
      checkpoint: 'SmilingWolf/wd-v1-4-convnext-tagger-v2'
    inference:
      device: 'cuda'
      batch_size: 20
  
  # input folder
  input:
    input_folder: '../dataset/fengpig'
    patterns:
      - '*.JPG'
      - '*.png'
    recursive: True
  
  # output folder
  output:
    output_folder: '../dataset/fengpig-blip' # if ignore, will use input_folder as output_folder
    image_column: 'image'
    caption_column: 'text'
    output_as_image_folder: True # if True, will generate metadata.csv and images
